---


- name: Install MySQL, Create User, and Run Query
  hosts: db_servers
  become: yes
  vars:
    mysql_root_password: "root"
    mysql_database: "uit"
    mysql_user: "lhs"
    mysql_password: "lhs"
  tasks:
    
    - name: install pip3
      apt: 
        name : python3-pip
        state: present

    - name: Install ansible python3 mysql dependency
      pip:
        name: pymysql
        state: present

    - name: create mysql directory
      file: 
        path: /var/lib/mysql
        state: directory

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Start MySQL service
      service:
        name: mysql
        state: started
      # mysql_user:
      #   login_user: root
      #   login_password: 'root2'
      #   name: root
      #   password: ''
      #   login_host: localhost
      #   check_implicit_admin: false
      #   login_unix_socket: /var/run/mysqld/mysqld.sock
