---

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php package
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      # update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: start apache server
    tags: apache,apache2,ubuntu
   # command: "systemctl start apache2"
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    tags: apache,apache2
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
