---
- name: Run MySQL Query from files
  hosts: db_servers[0]
  become: yes
  vars:
    mysql_user: lhs
    mysql_password: lhs
    mysql_database: uit
  tasks:
    - name: copy sql file 
      copy:
        src: query.sql
        dest: /home/lin/query.sql
        owner: root
        group: root
        mode: 0644


    - name: Execute MySQL query from file
      mysql_db:
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        name: "{{ mysql_database }}"
        # login_host: "{{ inventory_hostname }}"
        state: import
        target: /home/lin/query.sql
      # command: mysql -h  -u {{mysql_user}} -p {{mysql_password}} -D {{mysql_database}} < /path/to/your/script.sql

