---

- name: Remove ssh for web_servers
  hosts: web_servers  # Or specify specific hosts/group from your inventory
  become: yes
  tasks:

    - name: Remove SSH keys from authorized_keys
      authorized_key:
        user: "{{ item.name }}"
        state: absent
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOmJ908j7Ffd9+fLYZsQo8qqnztduhuJt29df923yd/C ansible"
      loop:
        - { name: dev1 }
        - { name: dev2 }
        - { name: test1 }
          

- name: remove ssh for database servers
  hosts: db_servers  # Or specify specific hosts/group from your inventory
  become: yes
  tasks:

    - name: Remove SSH keys from authorized_keys
      authorized_key:
        user: "{{ item.name }}"
        state: absent
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOmJ908j7Ffd9+fLYZsQo8qqnztduhuJt29df923yd/C ansible"
      loop:
        - { name: dev1 }
        - { name: dev2 }
        - { name: analyst1 }

- name: Remove User Groups and Users
  hosts: all  # Or specify specific hosts/group from your inventory
  become: yes
  tasks:
    - name: Remove user accounts
      user:
        name: "{{ item }}"
        state: absent
      loop:
        - dev1
        - dev2
        - test1
        - test2
        - analyst1

    - name: Remove groups
      group:
        name: "{{ item }}"
        state: absent
      loop:
        - developers
        - testers
        - analysts